# build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# si necesitas rewrite/SPA routing, copia un nginx.conf personalizado
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]